apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-pipeline-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-pipeline-demo
  template:
    metadata:
      labels:
        app: cicd-pipeline-demo
    spec:
      containers:
      - name: cicd-pipeline-demo
        image: mdsatan/cicd-pipeline-demo:5
        imagePullPolicy: Always
        ports: 
        - containerPort: 3000
          name: http

---

kind: Service             
apiVersion: v1            
metadata:                 
  name: cicd-pipeline-demo-service     
spec:                     
  selector:               
    app: cicd-pipeline-demo           
  ports:                  
  - protocol: TCP         
    targetPort: 3000      
    port: 3000
    nodePort: 30000        
    name: http   
  type: LoadBalancer    
